### ISSUE TITLE
希望能加入自定义滤镜/不带滤镜的功能.

### ISSUE THREAD

**Issue by PhoenixZeng** [lhing17/BlpConverter#1]
你也搞了个这工具啊,我本来打算自己写的.
希望能加入自定义滤镜/不带滤镜的功能.
[(滤镜指这种)](https://github.com/lhing17/BlpConverter/blob/master/src/main/resources/active_border.png)

现在的魔兽主动技能挺少有人带滤镜了.
自定义滤镜是为了方便加装备品级的边框之类的

ps:我做了一个jitpack.io版本的BLP_IIO_Plugins,可以考虑换上 毕竟本地安装jar包比较难受

**Comment by PhoenixZeng** [comment]
看了一下尽然是脚本形式的写法... 还以为是jar包来着

**Comment by lhing17** [comment]
第一个版本，主要满足自己使用来着，后面再慢慢完善

**Comment by lhing17** [comment]
已添加自定义滤镜/不带滤镜的功能
